### ISSUE TITLE
Can you explain what are those urls you put there are for?

### ISSUE THREAD

**Issue by patricechaula** [paynow/Paynow-Python-SDK#15]
I am seeing the code for creating a new Paynow instance. I don't understand what those urls are actually for. The documentation doesn't state anything about those urls `'http://google.com'`.

`paynow = Paynow(
	'INTEGRATION_ID',
	'INTEGRATION_KEY',
	'http://google.com',
	'http://google.com'
	)`

**Comment by adriankokai** [comment]
The first is for return url (where the user will be redirected to I think )
and the second is for result url ( where the result of the transaction will
be sent ). They used 'http://google.com' only as an example, you have to
replace the links with your own URLs i.e return url and result url.

see https://github.com/paynow/Paynow-Python-SDK/blob/master/paynow/model.py

**Comment by bevennyamande** [comment]
- Its confusing though thought they could just bundle the response in one instance and let the developer do what he wants with the response object

**Comment by ignertic** [comment]
Can you explain in more detail about your preference ?

**Comment by ignertic** [comment]
@adriankokai is correct. For Future reference you can always look at the docs over at https://developers.paynow.co.zw/docs

**Comment by bevennyamande** [comment]
just give one response then the developer choose to do what ever he wants with the response, since this is just an API call just return a json response

```python

resp = ResponseFromPaynow()
# No need for Return_url and result_url 

if resp.is_ok:
    return redirect(url_for('xyz'))
```

**Comment by bevennyamande** [comment]
I wrote my API long back before the Paynow API and i still feel its way more simple and straight forward to the point
